### ISSUE TITLE
Setting of data directory for learned data

### ISSUE THREAD

**Issue by hagenw** [TWOEARS/localisation-training-pipeline#1]
The output directory is at the moment specified in `get_data_root()`.

I would propose to remove this function completely and store the data directly under the corresponding data folder, which can be accessed via `xml.dbPath`. @ningma97 what do you think?

This is related to #2.

/CC @fietew @ryanckim @Hardcorehobel

**Comment by ningma97** [comment]
Fine by me. The get_data_root() is really a dirty trick to run the code in our grid computing system without having to use the WP1 code.

**Comment by hagenw** [comment]
Ok, but your grid computing is a valid point. At the end we should ensure, that we are still possible to run the code on a cluster without too much hassle.

**Comment by hagenw** [comment]
The data is now stored under `./learned_models/DnnLocationKS` and `./learned_models/GmmLocationKS`. This behavior is identical to the one from the old and now removed `GmtkLocationKS`, see http://docs.twoears.eu/en/1.0/examples/train-localisation/.
It has the advantage, that the Binaural Simulator first looks at a relative path for any data.

**Comment by hagenw** [comment]
The temporary feature folder (`DevFeatures_1deg_32channels` and `TrainFeatures_MCT-DIFFUSE_1deg_32channels`) are now stored in the temporary directory of the Binaural Simulator, that is defined by `xml.dbTmp`.
The training pipeline depends now on [twoears-main](https://github.com/TWOEARS/main) and the [binaural simulator](https://github.com/TWOEARS/binaural-simulator), but it should still be possible to use it on any kind of server, as the mex-files are not needed.
