### ISSUE TITLE
Storing of learned data

### ISSUE THREAD

**Issue by hagenw** [TWOEARS/localisation-training-pipeline#2]
This is related to #1.

Checkout the `cleanup` branch, specify an output dir in `get_data_root()` and run:

``` Matlab
>> f1_createBinauralFeatureDev(azimuthVector, azRes);

Error using writehtk (line 47)
Unable to create HTK file
/home/hagen/data/sound-localisation/DevFeatures_5deg_32channels/channel1/az0_s20_lgid2s_impulse_responses/twoears_kemar_adream/TWOEARS_KEMAR_ADREAM_pos2.sofa.htk

Error in f1_createBinauralFeatureDev (line 176)
                writehtk(htkfn, azFeatures);
```

I have checked and found the `/home/hagen/data/sound-localisation/DevFeatures_5deg_32channels/channel1` folder. I guess the problem is that the other needed sub-folders where not created. @ningma97 could you fix this?

\CC @ryanckim @Hardcorehobel

**Comment by ningma97** [comment]
Hmm... the htk format files need to saved in /home/hagen/data/sound-localisation/DevFeatures_5deg_32channels/channel1/ not in its subfolders. I don't understand how the other subfolder names got in there. It should be az0_s20_lgid2s_BRIR.htk where BRIR is the name of BRIR used...

**Comment by ningma97** [comment]
OK I think I've fixed this.

**Comment by hagenw** [comment]
Yes, thanks.
